name: 'setup-manifest'
description: |
  Set up R, renv and dependencies for a Posit Connect `manifest.json`
  file.

runs:
  using: composite
  steps:
    - name: Subscription check
      run: |
        # validate subscription status
        API_URL="https://agent.api.stepsecurity.io/v1/github/$GITHUB_REPOSITORY/actions/subscription"

        # Set a timeout for the curl command (3 seconds)
        RESPONSE=$(curl --max-time 3 -s -w "%{http_code}" "$API_URL" -o /dev/null) || true
        CURL_EXIT_CODE=$?

        # Decide based on curl exit code and HTTP status
        if [ $CURL_EXIT_CODE -ne 0 ]; then
          echo "Timeout or API not reachable. Continuing to next step."
        elif [ "$RESPONSE" = "200" ]; then
          :
        elif [ "$RESPONSE" = "403" ]; then
          echo "Subscription is not valid. Reach out to support@stepsecurity.io"
          exit 1
        else
          echo "Timeout or API not reachable. Continuing to next step."
        fi
      shell: bash

    - name: Create or update renv.lock
      run: |
        docker run -v "$PWD":/repo --workdir /repo \
          ghcr.io/r-hub/r-minimal/r-minimal:latest \
          R -q -e 'install.packages("renv", repos = "https://cran.rstudio.com"); renv:::renv_lockfile_from_manifest("manifest.json", "renv.lock")'
      shell: bash

    - name: Install R
      uses: step-security/r-lib-actions/setup-r@v2
      with:
        r-version: renv
        use-public-rspm: true

    - name: Install R packages via renv
      uses: step-security/r-lib-actions/setup-renv@v2
