name: Test setup-pandoc on all OSes

permissions: read-all

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:
    inputs:
      version:
        description: |
          Pandoc version, may be "latest".
        required: true
        default: '3.1.11'
        type: string

jobs:
  pandoc:
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os }}

    strategy:
      fail-fast: false
      matrix:
        config:
          - { os: macos-14         }
          - { os: macos-13         }
          - { os: windows-latest   }
          - { os: ubuntu-latest    }
          - { os: ubuntu-22.04-arm }

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@002fdce3c6a235733a90a27c80493a3241e56863 # v2.12.1
        with:
          egress-policy: audit

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - uses: ./setup-pandoc
        with:
          pandoc-version: ${{ github.event.inputs.version || '3.1.11' }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - run: pandoc --version

      - run: which pandoc
        if: ${{ runner.os == 'Linux' || runner.os == 'macOS' }}

      - run: where.exe pandoc
        if: ${{ runner.os == 'Windows' }}
